services:
  data_collection_service:
    image: python:3
    container_name: data_collector_container
    volumes:
      - ./data_collection_module:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - DATABASE_URL = "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_service/${POSTGRES_DB}"
    command: "sh -c 'pip install -r requirements.txt && additional_programs/transfer_products_from_file_to_db.py && python app.py'"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 128M
    depends_on:
      - db_service
    restart: unless-stopped

  db_service:
    image: postgres
    container_name: data_base_container
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
    volumes:
      - ${DB_INIT_SCRIPT}:/docker-entrypoint-initdb.d/create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  db-data:
