services:
  data_collection_service:
    image: python:3
    container_name: data_collector_container
    volumes:
      - ./data_collection_module:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_service/${POSTGRES_DB}"
    command: "bash -c 'python3 -m venv myenv && source myenv/bin/activate && pip install -r requirements.txt && python3 transfer_products_from_file_to_db.py && python app.py'"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 128M
    depends_on:
      - db_service
    restart: unless-stopped

  integration_service:
    image: python:3
    container_name: integration_module_container
    volumes:
      - ./integration_module:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - "DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db_service/${POSTGRES_DB}"
      - "PREDICTOR_PORT=${PREDICTOR_PORT}"
      - "PREDICTOR_HOST=prophet_forecasting_module"
      - "MIN_INPUT_WINDOW_SIZE=${MIN_INPUT_WINDOW_SIZE}"
      - "MAX_INPUT_WINDOW_SIZE=${MAX_INPUT_WINDOW_SIZE}"
    ports:
      - "8080:8000"
    command: "bash -c 'python3 -m venv myenv && source myenv/bin/activate && pip install -r requirements.txt && python3 app.py'"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.05"
          memory: 128M
    depends_on:
      - db_service
      - prophet_forecasting_module
    restart: unless-stopped

  prophet_forecasting_module:
    image: python:3
    container_name: prophet_forecasting_container
    volumes:
      - ./prophet_forecasting_module:/app
    working_dir: /app
    env_file:
      - .env
    environment:
      - "PREDICTOR_PORT=${PREDICTOR_PORT}"
    command: "bash -c 'python3 -m venv myenv && source myenv/bin/activate && pip install -r requirements.txt && python3 prophet_forecasting_service.py'"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 2G
        reservations:
          cpus: "0.5"
          memory: 128M
    restart: unless-stopped

  db_service:
    image: postgres
    container_name: data_base_container
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
    volumes:
      - ${DB_INIT_SCRIPT}:/docker-entrypoint-initdb.d/create_db.sql
      - ./db_data:/var/lib/postgresql/data
    restart: unless-stopped


#volumes:
#  db-data:
